[0m01:59:51.946655 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027842B1E470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027843DBCD00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027843DBCC10>]}


============================== 01:59:51.954255 | e9e20446-2912-4e44-9573-ecb4b7fac568 ==============================
[0m01:59:51.954255 [info ] [MainThread]: Running with dbt=1.10.3
[0m01:59:51.954255 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mudga\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt run', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'send_anonymous_usage_stats': 'True'}
[0m01:59:51.954255 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\Data_Engineering_Projects\ELT_Pipeline_Using_Snowflake\dbt-dag\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m01:59:51.954255 [debug] [MainThread]: Command `dbt run` failed at 01:59:51.954255 after 0.17 seconds
[0m01:59:51.954255 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027842B1E470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027843DBF1F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000027843DBE6E0>]}
[0m01:59:51.954255 [debug] [MainThread]: Flushing usage events
[0m01:59:53.482268 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:32:03.063509 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6CD5E500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6EFCFBB0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6EFCE140>]}


============================== 00:32:03.072093 | 34a29bde-4dcb-4781-9aaf-db991d41ebb7 ==============================
[0m00:32:03.072093 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:32:03.072093 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'fail_fast': 'False', 'log_path': 'logs', 'debug': 'False', 'profiles_dir': 'C:\\Users\\mudga\\.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'invocation_command': 'dbt run -s fct_orders', 'static_parser': 'True', 'log_format': 'default', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m00:32:03.072093 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path E:\Data_Engineering_Projects\ELT_Pipeline_Using_Snowflake\dbt_dag\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m00:32:03.076140 [debug] [MainThread]: Command `dbt run` failed at 00:32:03.076140 after 0.14 seconds
[0m00:32:03.076140 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6CD5E500>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6EFCC9D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000021D6EFCD180>]}
[0m00:32:03.077677 [debug] [MainThread]: Flushing usage events
[0m00:32:04.800642 [debug] [MainThread]: An error was encountered while trying to flush usage events
[0m00:49:32.097190 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188083FE470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001880A66FCA0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001880A66E080>]}


============================== 00:49:32.102919 | 8c2da02a-2581-4d82-b588-0a18713111a7 ==============================
[0m00:49:32.102919 [info ] [MainThread]: Running with dbt=1.10.3
[0m00:49:32.104048 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\mudga\\.dbt', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptionsV2(error=[], warn=[], silence=[])', 'target_path': 'None', 'invocation_command': 'dbt debug', 'send_anonymous_usage_stats': 'True'}
[0m00:49:32.148721 [info ] [MainThread]: dbt version: 1.10.3
[0m00:49:32.149721 [info ] [MainThread]: python version: 3.10.0
[0m00:49:32.149721 [info ] [MainThread]: python path: C:\Users\mudga\AppData\Local\Programs\Python\Python310\python.exe
[0m00:49:32.150721 [info ] [MainThread]: os info: Windows-10-10.0.22631-SP0
[0m00:49:33.830647 [info ] [MainThread]: Using profiles dir at C:\Users\mudga\.dbt
[0m00:49:33.830647 [info ] [MainThread]: Using profiles.yml file at C:\Users\mudga\.dbt\profiles.yml
[0m00:49:33.831681 [info ] [MainThread]: Using dbt_project.yml file at E:\Data_Engineering_Projects\ELT_Pipeline_Using_Snowflake\dbt_dag\dbt_project.yml
[0m00:49:33.833683 [info ] [MainThread]: adapter type: snowflake
[0m00:49:33.834683 [info ] [MainThread]: adapter version: 1.9.4
[0m00:49:33.834683 [info ] [MainThread]: Configuration:
[0m00:49:33.835681 [info ] [MainThread]:   profiles.yml file [[32mOK found and valid[0m]
[0m00:49:33.836695 [info ] [MainThread]:   dbt_project.yml file [[31mERROR not found[0m]
[0m00:49:33.837648 [info ] [MainThread]: Required dependencies:
[0m00:49:33.838650 [debug] [MainThread]: Executing "git --help"
[0m00:49:33.891762 [debug] [MainThread]: STDOUT: "b"usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]\n           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]\n           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]\n           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]\n           [--super-prefix=<path>] [--config-env=<name>=<envvar>]\n           <command> [<args>]\n\nThese are common Git commands used in various situations:\n\nstart a working area (see also: git help tutorial)\n   clone     Clone a repository into a new directory\n   init      Create an empty Git repository or reinitialize an existing one\n\nwork on the current change (see also: git help everyday)\n   add       Add file contents to the index\n   mv        Move or rename a file, a directory, or a symlink\n   restore   Restore working tree files\n   rm        Remove files from the working tree and from the index\n\nexamine the history and state (see also: git help revisions)\n   bisect    Use binary search to find the commit that introduced a bug\n   diff      Show changes between commits, commit and working tree, etc\n   grep      Print lines matching a pattern\n   log       Show commit logs\n   show      Show various types of objects\n   status    Show the working tree status\n\ngrow, mark and tweak your common history\n   branch    List, create, or delete branches\n   commit    Record changes to the repository\n   merge     Join two or more development histories together\n   rebase    Reapply commits on top of another base tip\n   reset     Reset current HEAD to the specified state\n   switch    Switch branches\n   tag       Create, list, delete or verify a tag object signed with GPG\n\ncollaborate (see also: git help workflows)\n   fetch     Download objects and refs from another repository\n   pull      Fetch from and integrate with another repository or a local branch\n   push      Update remote refs along with associated objects\n\n'git help -a' and 'git help -g' list available subcommands and some\nconcept guides. See 'git help <command>' or 'git help <concept>'\nto read about a specific subcommand or concept.\nSee 'git help git' for an overview of the system.\n""
[0m00:49:33.891762 [debug] [MainThread]: STDERR: "b''"
[0m00:49:33.893270 [info ] [MainThread]:  - git [[32mOK found[0m]

[0m00:49:33.894276 [info ] [MainThread]: Connection:
[0m00:49:33.895278 [info ] [MainThread]:   account: mf02624.ap-south-1.aws
[0m00:49:33.896277 [info ] [MainThread]:   user: mudgalabhay
[0m00:49:33.896277 [info ] [MainThread]:   database: dbt_db
[0m00:49:33.897282 [info ] [MainThread]:   warehouse: dbt_warehouse
[0m00:49:33.898282 [info ] [MainThread]:   role: dbt_role
[0m00:49:33.899284 [info ] [MainThread]:   schema: dbt_schema
[0m00:49:33.900284 [info ] [MainThread]:   authenticator: None
[0m00:49:33.900284 [info ] [MainThread]:   oauth_client_id: None
[0m00:49:33.901284 [info ] [MainThread]:   query_tag: None
[0m00:49:33.902447 [info ] [MainThread]:   client_session_keep_alive: False
[0m00:49:33.902990 [info ] [MainThread]:   host: None
[0m00:49:33.904034 [info ] [MainThread]:   port: None
[0m00:49:33.904998 [info ] [MainThread]:   proxy_host: None
[0m00:49:33.904998 [info ] [MainThread]:   proxy_port: None
[0m00:49:33.905999 [info ] [MainThread]:   protocol: None
[0m00:49:33.906998 [info ] [MainThread]:   connect_retries: 1
[0m00:49:33.907998 [info ] [MainThread]:   connect_timeout: None
[0m00:49:33.909027 [info ] [MainThread]:   retry_on_database_errors: False
[0m00:49:33.909027 [info ] [MainThread]:   retry_all: False
[0m00:49:33.909996 [info ] [MainThread]:   insecure_mode: False
[0m00:49:33.911506 [info ] [MainThread]:   reuse_connections: True
[0m00:49:33.912516 [info ] [MainThread]: Registered adapter: snowflake=1.9.4
[0m00:49:34.494343 [debug] [MainThread]: Acquiring new snowflake connection 'debug'
[0m00:49:34.732173 [debug] [MainThread]: Using snowflake connection "debug"
[0m00:49:34.733169 [debug] [MainThread]: On debug: select 1 as id
[0m00:49:34.734198 [debug] [MainThread]: Opening a new connection, currently in state init
[0m00:49:35.691698 [debug] [MainThread]: SQL status: SUCCESS 1 in 0.958 seconds
[0m00:49:35.692697 [info ] [MainThread]:   Connection test: [[32mOK connection ok[0m]

[0m00:49:35.693697 [info ] [MainThread]: [31m1 check failed:[0m
[0m00:49:35.694697 [info ] [MainThread]: Project loading failed for the following reason:
 project path <E:\Data_Engineering_Projects\ELT_Pipeline_Using_Snowflake\dbt_dag\dbt_project.yml> not found

[0m00:49:35.695697 [debug] [MainThread]: Command `dbt debug` failed at 00:49:35.695697 after 3.72 seconds
[0m00:49:35.696697 [debug] [MainThread]: Connection 'debug' was left open.
[0m00:49:35.697202 [debug] [MainThread]: On debug: Close
[0m00:49:35.792605 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188083FE470>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000018823597490>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000188239DBEE0>]}
[0m00:49:35.792605 [debug] [MainThread]: Flushing usage events
[0m00:49:37.162653 [debug] [MainThread]: An error was encountered while trying to flush usage events
